### ISSUE TITLE
Confining margins is failing now

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/ConfinementTool#24]
So I have tried out the new update, everything is projected in UTM, disabled M and Z values. When running confining margins it gets all the way through and then fails at the end. Its still creating outputs within the path Outputs<Conefinement_001< ConfiningMargins. But this is the error I keep getting, Ive tried naming the realization something different but get the same error everytime.
![capture](https://user-images.githubusercontent.com/30604787/28839714-ce68c704-76b1-11e7-93e2-df08b62dc826.PNG) So since the outputs were actually created I tried moving on to analysis anyways, but when I get to the spot to choose which realization to input It doesnt recognize any from within the project.
So it seems the confining margins tool is failing to attribute the outputs with any associated realization.

**Comment by aagervasi** [comment]
This also occurred for me. Confining margins ran successfully when I switched back to version 2.1.02 from 2.1.03, so it has something to do with a difference between the two versions. The data set used was:
https://www.dropbox.com/home/Riverscapes_share?preview=FailedConfinementRun.zip

Also, when I go to run Confinement on a Segmented Network, I am still having the issue where the tool uses the Riverscapes xml to find the input segment stream network and the auto-load will fail UNLESS I name the original project Realization (created during Confining Margins step) "Confinement_001" --wanted to mention here in case the issue was related. Thanks!
(successful upload below)
![confin_segnetwork](https://user-images.githubusercontent.com/25061462/29422004-abf3edda-832b-11e7-9ea5-7813d4b2daae.png)
