### ISSUE TITLE
Assigning Flood Defence structure to Confinement Margin

### ISSUE THREAD

**Issue by Hornbydd** [Riverscapes/ConfinementTool#32]
I have created a model that creates a non-spatial table assigning structure length to a margin ID.

![image](https://user-images.githubusercontent.com/22773948/45228668-b6c82a80-b2bb-11e8-9410-987676b9a4ff.png)

It has a user friendly interface to it.

![image](https://user-images.githubusercontent.com/22773948/45228715-d8c1ad00-b2bb-11e8-9b85-7aaa0db1bc1e.png)

The logic is as:

1. Buffer Confinement Margins
2. Intersect Buffers with EA flood defence lines
3. Summarise lengths by margin ID
4. Export to user specified table.

This table can be joined back to the confinement margins layer by the marginsID field.

By virtue that the marginID is recorded in this output table is must be near a structure. If the ID does not exist in the output table then the confinement margin buffer never intersected any flood defence line.

**Potential issues**

- The buffer is a classic full buffer (a flat end one was creating wacky polygons) and thus buffers out left and right. So a confinement line will intersect structures in front and behind it.

- The current model does not attempt to record type of structure, just that it exists. But as the input flood dataset would be the output of the _Select and Export a sub-set of assets from UK flood defence dataset_ tool it will contain only the relevant structures (e.g. walls/embankments)

- If you make the buffer too big then it will select structures on the opposite bank.

**Comment by joewheaton** [comment]
Nice one @Hornbydd. Just a question. So I can see how having this inventory is useful. Is the idea that we'll later use this to calculate:
- Proportion of confinement within a reach that is provided by anthropogenic confining margins (specifically flood defenses)?
- To summarize length (by reach) of flood defnense margins that are actively confining?
- To identify (map) locations that are actively confined by anthropogenic margins (seems like you nailed that)?
- To differentiate anthropogenic margins that are just overlaid on top of natural confining margins versus those that are new?
- To calculate proportion of constriction caused by anthropogenic margin?

Anything else? I can see how above is useful, but it would be helpful to know where we're going with it.

Also, I'm curious about whether this can be genericized from something that just works for 'flood defense' and instead can be any anthropogenic margin, and we just add an optional field of anthro-type or something?

**Comment by Hornbydd** [comment]
I would say the first four bullet points are **yes**, the output of this tool can be used to compute those metrics.

The current model logic takes a confinement margin, buffers and intersects with any flood defence line to summarise for the confinement margin _as a whole_. As I understand it a _constriction_ occurs when both left and right are recording confined. The tool is not currently designed to summarise at that level so your last bullet point won't work. That's not to say I can't get it up and running. This model is working at the level of a whole confinement ID and not lower level attribution.

I believe the tool is "generic" in that the lines could represent anything else that happens to be running alongside the river. The model is not filtering on type it is simply an intersection of the buffer with a polyline dataset and then subsequent summarising of lengths. The only thing it is expecting to exist is a `MarginID` field in the input confinement layer.

**Comment by Hornbydd** [comment]
I would say the first four bullet points are **yes**, the output of this tool can be used to compute those metrics.

The current model logic takes a confinement margin, buffers and intersects with any flood defence line to summarise for the confinement margin _as a whole_. As I understand it a _constriction_ occurs when both left and right are recording confined. The tool is not currently designed to summarise at that level so your last bullet point won't work. That's not to say I can't get it up and running. This model is working at the level of a whole confinement ID and not lower level attribution.

I believe the tool is "generic" in that the lines could represent anything else that happens to be running alongside the river. The model is not filtering on type it is simply an intersection of the buffer with a polyline dataset and then subsequent summarising of lengths. The only thing it is expecting to exist is a `MarginID` field in the input confinement layer.

**Comment by Hornbydd** [comment]
Tool is complete and no further development is currently planned. It is likely that it will require further development if we try to roll it out for national level processing.
