### ISSUE TITLE
Creating valley cross sections

### ISSUE THREAD

**Issue by Hornbydd** [Riverscapes/ConfinementTool#44]
@dsear  - A key processing step to computing any floodplain metric (#41) is generating a sensible floodplain cross section from the river centre line segment. For that to work we need a sensible valley centre line, which I have been able to compute  #39.

I have been able to work up the logic in a model that generates valley cross sections and it is working well.

![Model](https://user-images.githubusercontent.com/22773948/48620596-a3f76380-e998-11e8-86ae-789b42c7961a.png)

The output of the model generates the valley cross sections as shown in black below:

![Valley Cross sections](https://user-images.githubusercontent.com/22773948/48620631-c5f0e600-e998-11e8-8320-c6444e6dddf6.png)

Be aware that cross sections terminate at the edge of the flood map polygon, so internal holes will create shorter cross sections, an example is shown below:

![A short Valley Cross section](https://user-images.githubusercontent.com/22773948/48620738-0a7c8180-e999-11e8-9c6b-6de1b4ea2e15.png)

The tool logic is:

- Get centroid of river segment
- Find nearest point on valley centrelines
- Construct a line between these two point locations
- Do some data preparation (to deal with performance/data volume)
- Use the extend line tool to extend the initial line out to the edge of the flood map polygon
- Clean up datasets

### Hard wired Model properties (which can be easily changed) are:

- Output coordinate system is British National Grid
- The tool searches up to 1Km when trying to identify a flood map polygon edge.

### Limitations
- User requires an Advance license because of tools it uses.
- The Extend Line tool works a treat but is slow, something you have to accept.

**Comment by Hornbydd** [comment]
Apart from cross sections be "cut short" because of holes in the flood zone map, here is a pathological case of a hole causing another cross section at a tributary junction not crossing the floodplain.

![Problem](https://user-images.githubusercontent.com/22773948/48631431-69042880-e9b6-11e8-82a8-5b1ccb61e77b.png)

This happens to be the only case out of 71 cross sections, so my advise to firstly myself and then other users of this tool is to double check output and correct as necessary as 2% of the data will be incorrect, not bad really! :)

**Comment by Hornbydd** [comment]
@dsear & @joewheaton  - OK been exploring the next step of creating partitions of the floodplain using the valley cross sections, below is an example of when the data is "nice and simple". Here river segments create nice cross sections which where intersected with flood zone polygons to create sensible partitions. In this screen shot we see 1 segment selected, the points are the split points labelled with distance, the red point is a bridge.

![good data](https://user-images.githubusercontent.com/22773948/48635154-46c2d880-e9bf-11e8-8b10-27406d1c6994.png)

BUT! I have hit a snag with regards to "holes" in the floodplain which **needs a decision**. Examine image below:

![hole effect](https://user-images.githubusercontent.com/22773948/48634047-99e75c00-e9bc-11e8-91b7-9aab0a777b9e.png)

The red hashed area is a single polygon. the cross section in the middle terminates at a hole, this termination means what would normally be left and right polygons are able to join. This topological problem and the sensible partitioning up of the floodplain can only be resolved by removing the holes. 

If removal of the holes are done before valley centre line creation then that purple line (the valley centreline) will also shift.

The implication of removing holes prior to processing are that it would generate more realistic cross sections but would ignore the fact that there are topographic highest with the flood plain, which could be causing confinement (I'm thinking embankments on the floodplain).

As I am creating the cross section from the middle of the river segment, all segments intersect  2 partitions. This can be seen by the fact I have selected a single segment (cyan)

![Always 2 partitions](https://user-images.githubusercontent.com/22773948/48634418-648f3e00-e9bd-11e8-9871-0c2ec6867dd7.png)

Now as segments always intersect 2 partitions I'm wondering if we don't worry about this merging of partition polygons? Although here is an example of multiple holes causing 3 partitions to merge.

![Multi-merge](https://user-images.githubusercontent.com/22773948/48634766-4a099480-e9be-11e8-8cde-244b68c79b84.png)

The implication is that some segments will intersect multiple partitions when holes exist, so would need to normalise land cover values.

**Comment by Hornbydd** [comment]
I'm going to assume that you are happy for me not to remove holes so a cross section can be circumvented and floodplain partitions can merge into larger partitions when holes exist. Does mean less coding for me!

Unless you say otherwise...

I have augmented the valley cross section tool to allow you to choose if you want to create the valley cross section at the mid point of the river segment or it's end points. The current tool interface is now this:

![Valley cross section tool interface.](https://user-images.githubusercontent.com/22773948/48707685-216cdf00-ebf8-11e8-8ba7-366d3d89c54c.png)

**Comment by Hornbydd** [comment]
For the create valley cross section tool I have removed the parameter that allows you to select the mid-point or end-points of a segment for creating the cross sections. It now only ever creates them at the end-points.  This is in preparation for creating the tool that computes the expansion:contraction ratio.

**Comment by Hornbydd** [comment]
@dsear, 

Been doing some awesome coding!

I have developed the tool that identifies and fills in the holes in the valley bottom (flood zone 2 map) based upon a positive 3m elevation difference. The logic is:

- Convert valley bottom to lines then back into polygons to pull out internal rings or "holes" and add a few attributes.
- This temporary polygon dataset is then cycled over looking at each polygon.
- The polygon is rasterized, expanded by 1 cell and masked to create a ring of pixels around the rasterized polygon. 
- These  two raster datasets are then used in zonal stats tool to extract the mean elevation from the OS 5m Terrain dataset.
- If the mean elevation within the polygon is at least 3m or higher than the mean elevation of the ring of pixels then the polygon is tagged as keep.
- Polygons tagged as drop are merged backed into the floodzone map and then dissolved to remove them.

Before:

![Before](https://user-images.githubusercontent.com/22773948/48954098-007df400-ef40-11e8-9c90-2339f5b89274.png)

After (arrow indicates a hole where the mean elevation it encloses is higher than its immediate surroundings):

![After](https://user-images.githubusercontent.com/22773948/48954127-25726700-ef40-11e8-88b0-3827e43beca6.png)

**Comment by dsear** [comment]
Your da man!  Top work Duncan….are we nearly there yet for Derwent?

Cheers

David

Professor David Sear
School of Geography
University of Southampton
++44 (0)2380 592215(Office)
++44 (02380 594614 (Direct)
Email:d.sear@soton.ac.uk
Twitter:@sedimentsystem
ORCID:0000-0003-0191-6179<http://orcid.org/0000-0003-0191-6179>
http://www.southampton.ac.uk/geography/staff_profiles/academic/ds5.html
http://www.nercpatches.org
http://www.dunwich.org.uk<http://www.dunwich.org.uk/>

**Comment by Hornbydd** [comment]
@dsear, OK have re-run valley centreline creation steps with new valley bottom (most holes removed) and then the valley cross sections tool, output is below.

![New data](https://user-images.githubusercontent.com/22773948/49032225-fb20e380-f1a3-11e8-8e22-47d3628811ed.png)

The purple line is the new valley centreline. The red dash cross sections are the cross sections built using the valley bottom WITH holes.  Note how some just seem to stop in the middle of the floodplain, this is where the hole edges were. The black cross sections are now the new cross sections built from the valley bottom polygon with hols REMOVED. They are providing sensible cross sectional lines for partitioning up the floodplain.

**Comment by dsear** [comment]
Looks sensible to me
D

Sent from my iPhone

On 28 Nov 2018, at 17:25, Duncan Hornby <notifications@github.com<mailto:notifications@github.com>> wrote:


@dsear<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdsear&data=01%7C01%7Cd.sear%40soton.ac.uk%7C9ea51e7667c04af2b92608d6555677bb%7C4a5378f929f44d3ebe89669d03ada9d8%7C1&sdata=TQy6S2%2B7vYASRjcCI10AXnRoY7iXQ%2FDxufQ1mFQD2gY%3D&reserved=0>, Since bumping into you at lunch I've been working of a way to automate the clipping back of tributaries. I have a methodology what do you think?

Here is the problem, partitioning along the main stem will eventually include tributaries, as shown by the selection:

[Problem]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22773948%2F49169152-18cf8380-f331-11e8-9b59-d34db9ac713c.png&data=01%7C01%7Cd.sear%40soton.ac.uk%7C9ea51e7667c04af2b92608d6555677bb%7C4a5378f929f44d3ebe89669d03ada9d8%7C1&sdata=Cd6WTTn2NK5%2F2w6DvpvGngRHCQXg8WSuuE6xsUSojzE%3D&reserved=0>

I have developed a model that takes the partition polygon, converts it into it's constituent vertices and measures the straight line distance to the segment that the partition was built around. Logic is that the partition boundary should not be much further away than the longest valley cross section. This logic identifies the above as a candidate to deal with.

If I then buffer the segment by the longest cross sectional width and then use that buffer to INTERSECT with the Selected partition polygon I get this:

[Intersect]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22773948%2F49169435-a57a4180-f331-11e8-9d4f-cc7b9f4b607a.png&data=01%7C01%7Cd.sear%40soton.ac.uk%7C9ea51e7667c04af2b92608d6555677bb%7C4a5378f929f44d3ebe89669d03ada9d8%7C1&sdata=99nhw06X%2F1h7s%2FHl95enJt9hRJhZE4v9nUJZAUIYH9o%3D&reserved=0>

I personally think this is a good compromise? Yes it does go up a bit of the tributary but not miles.

The same logic applied to this candidate partition generates this output:

[Another example]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22773948%2F49169581-f722cc00-f331-11e8-8910-7dbf6e3b49e2.png&data=01%7C01%7Cd.sear%40soton.ac.uk%7C9ea51e7667c04af2b92608d6555677bb%7C4a5378f929f44d3ebe89669d03ada9d8%7C1&sdata=NepfJL7mLrsn7VLEchDdSKGY7I%2Fgn2MrXQVOhOfhU1I%3D&reserved=0>

The blue arrow is pointing to the fact that buffer is clipping out what could be legitimate floodplain land use, but it is stopping it from going upstream on the R/B side.

**Comment by Hornbydd** [comment]
OK I'll turn the logic into a functioning tool for clipping out a section of floodplain and _replacing_ the existing partition polygon. Will update here when completed and tested.

**Comment by Hornbydd** [comment]
@dsear - OK the tool has been built, it requires minimal intervention, basically you need to pre-select the polygons where ToCheck = "Y", this is a field I added to the partition dataset to identify candidates for fixing. Problem is that there are nutty topological scenarios where one needs to drop from the selection or do a minor tweak before running this tool. Having got the selection sorted, run the tool. It appends the fixed polygons back into the dataset but does not automatically remove the original "offending polygon". I do this as it gives me the option to reject the fix, if I think the original was actually OK. So assuming the original polygons were all wrong then its a simple matter of selecting the polygons where ToCheck ="Y" and deleting them out as the append polygons are set to "C".

So here is the output:

![Output](https://user-images.githubusercontent.com/22773948/49231088-129cde00-f3e9-11e8-8ab0-08b104f1fd63.png)

Black lines are the valley cross sections, the red polygon is the original floodzone map and blue are the partitioned floodplain, note the blue now does not include upstream tribs.

**Comment by Hornbydd** [comment]
Tool is complete and no further development is currently planned. It is likely that it will require further development if we try to roll it out for national level processing.

**Comment by joewheaton** [comment]
@philipbaileynar, @KellyMWhitehead and @lauren-herbine did you guys ever see these posts? Quite relevant.
